trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'acrName'
  appServicePlanName: 'aspName'
  backendAppName: 'backendApp'
  frontendAppName: 'frontendApp'
  location: 'East US'
  resourceGroupName: 'rg-core-0001'

jobs:
- job: BuildAndDeployBackend
  displayName: 'Build and Deploy Backend'
  steps:
    - task: Docker@2
      displayName: 'Build Docker Image for Backend'
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'AzureContainerRegistry' 
        repository: 'backend'
        dockerfile: 'backend/Dockerfile'  # Path to your Dockerfile
        tags: |
          latest

    - task: AzureCLI@2
      displayName: 'Deploy ARM Template'
      inputs:
        azureSubscription: 'AzureServiceConnection'  # Name of your service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location) || echo "Resource group already exists"
          az deployment group create --resource-group $(resourceGroupName) --template-file azure-deployment-template.json --parameters acrName=$(acrName) appServicePlanName=$(appServicePlanName) backendAppName=$(backendAppName) frontendAppName=$(frontendAppName)
